name: Fetch Project Info
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fetch-project-info:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}   # <- no gh auth step needed
    steps:
      - name: Fetch fields from ProjectV2
        run: |
          PROJECT_ID="PVT_kwHOCXv9ec4BDT_9"
          gh api graphql --field project="$PROJECT_ID" -f query='
            query($project: ID!) {
              node(id: $project) {
                ... on ProjectV2 {
                  id
                  fields(first: 20) {
                    nodes {
                      __typename
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options { id name }
                      }
                    }
                  }
                }
              }
            }'
